### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by mauricioabreu** [mauricioabreu/todo-backend-kemal#6]
In order to have a runnable app we need to deploy it.

Here is a walkthrough to deploy a Crystal app to Heroku: https://crystal-lang.org/2016/05/26/heroku-buildpack.html

**Comment by mauricioabreu** [comment]
Thanks @rzanluchi 

URL for the project: http://todo-backend-kemal1.herokuapp.com/todos

**Comment by rzanluchi** [comment]
http://www.todobackend.com/specs/index.html?https://todo-backend-kemal1.herokuapp.com/todos

**Comment by mauricioabreu** [comment]
Cool! :+1:
